// This file will be auto-generated by running: npm run types:supabase
// Run the command after updating your database schema to regenerate types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      brand_snapshot_reports: {
        Row: {
          id: string
          report_id: string
          user_email: string | null
          user_name: string | null
          email: string | null
          company: string | null
          company_name: string | null
          brand_alignment_score: number | null
          pillar_scores: Json | null
          pillar_insights: Json | null
          recommendations: Json | null
          website_notes: string | null
          full_report: Json | null
          summary: string | null
          overall_interpretation: string | null
          opportunities_summary: string | null
          upgrade_cta: string | null
          snapshot_upsell: string | null
          weakest_pillar: string | null
          strengths: string[] | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          report_id: string
          user_email?: string | null
          user_name?: string | null
          email?: string | null
          company?: string | null
          company_name?: string | null
          brand_alignment_score?: number | null
          pillar_scores?: Json | null
          pillar_insights?: Json | null
          recommendations?: Json | null
          website_notes?: string | null
          full_report?: Json | null
          summary?: string | null
          overall_interpretation?: string | null
          opportunities_summary?: string | null
          upgrade_cta?: string | null
          snapshot_upsell?: string | null
          weakest_pillar?: string | null
          strengths?: string[] | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          report_id?: string
          user_email?: string | null
          user_name?: string | null
          email?: string | null
          company?: string | null
          company_name?: string | null
          brand_alignment_score?: number | null
          pillar_scores?: Json | null
          pillar_insights?: Json | null
          recommendations?: Json | null
          website_notes?: string | null
          full_report?: Json | null
          summary?: string | null
          overall_interpretation?: string | null
          opportunities_summary?: string | null
          upgrade_cta?: string | null
          snapshot_upsell?: string | null
          weakest_pillar?: string | null
          strengths?: string[] | null
          created_at?: string
          updated_at?: string
        }
      }
      brand_snapshot_plus_reports: {
        Row: {
          id: string
          report_id: string
          user_email: string | null
          user_name: string | null
          brand_alignment_score: number | null
          pillar_scores: Json | null
          pillar_insights: Json | null
          recommendations: Json | null
          website_notes: string | null
          full_report: Json | null
          enriched_persona: Json | null
          enriched_archetype: Json | null
          enriched_voice: Json | null
          enriched_color_palette: Json | null
          opportunities_map: string | null
          roadmap_30: string | null
          roadmap_60: string | null
          roadmap_90: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          report_id: string
          user_email?: string | null
          user_name?: string | null
          brand_alignment_score?: number | null
          pillar_scores?: Json | null
          pillar_insights?: Json | null
          recommendations?: Json | null
          website_notes?: string | null
          full_report?: Json | null
          enriched_persona?: Json | null
          enriched_archetype?: Json | null
          enriched_voice?: Json | null
          enriched_color_palette?: Json | null
          opportunities_map?: string | null
          roadmap_30?: string | null
          roadmap_60?: string | null
          roadmap_90?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          report_id?: string
          user_email?: string | null
          user_name?: string | null
          brand_alignment_score?: number | null
          pillar_scores?: Json | null
          pillar_insights?: Json | null
          recommendations?: Json | null
          website_notes?: string | null
          full_report?: Json | null
          enriched_persona?: Json | null
          enriched_archetype?: Json | null
          enriched_voice?: Json | null
          enriched_color_palette?: Json | null
          opportunities_map?: string | null
          roadmap_30?: string | null
          roadmap_60?: string | null
          roadmap_90?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

