// app/api/og/report/route.ts
// Dynamic Open Graph image generation for Brand Snapshot reports
// Usage: /api/og/report?score=78

import { ImageResponse } from "next/og";

export const runtime = "edge";

export async function GET(req: Request) {
  const { searchParams } = new URL(req.url);
  const score = searchParams.get("score") || "—";

  return new ImageResponse(
    (
      <div
        style={{
          width: "1200px",
          height: "630px",
          background: "#021859",
          color: "white",
          display: "flex",
          flexDirection: "column",
          padding: "60px",
          justifyContent: "center",
          fontFamily: "Helvetica Neue, sans-serif"
        }}
      >
        <h1 style={{ fontSize: 56, marginBottom: 20 }}>
          Your Brand Snapshot™ Results
        </h1>
        
        <p style={{ fontSize: 32, marginBottom: 40 }}>
          Brand Alignment Score: <strong>{score}</strong>
        </p>

        <div
          style={{
            fontSize: 24,
            opacity: 0.9,
          }}
        >
          Generated by Wundy • Wunderbar Digital
        </div>
      </div>
    ),
    { width: 1200, height: 630 }
  );
}

