/**
 * Paste-ready email lifecycle: subjects, preheaders, body copy, hero image prompts, and CTAs.
 * Wired from diagnostic derivatives (company, audience, pillars, priorities).
 */
export type EmailLifecycleDerivatives = {
  companyName: string;
  industry: string;
  primaryPillar: string;
  firstPriority: string;
  secondPriority: string;
  thirdPriority: string;
  audienceShort: string;
};

export function buildDevelopedEmailLifecyclePlan(d: EmailLifecycleDerivatives): string {
  const cn = d.companyName;
  const ind = d.industry.toLowerCase();
  const pillar = d.primaryPillar.toLowerCase();
  const p1 = d.firstPriority.toLowerCase();
  const p2 = d.secondPriority.toLowerCase();
  const p3 = d.thirdPriority.toLowerCase();
  const aud = d.audienceShort;

  return [
    "## Starter nurture sequence (paste-ready)",
    "",
    "Use merge tags (`{{first_name}}`, `{{company}}`) in your ESP. Swap metrics with real proof when available. Each **Email N** block below is one send: subject line → preheader (inbox preview) → body → prompts → CTAs.",
    "",
    "## Email 1 — Awareness",
    `- **Subject line:** Still seeing qualified interest leak after you fix the ad?`,
    `- **Preheader (inbox preview):** A 3-minute read for ${aud} on ${pillar} drift.`,
    `- **Hero image prompt:** Split 1200×628 layout: left panel noisy analytics UI (muted reds), right calm laptop showing one headline + proof strip for ${cn}; daylight office, navy #021859 and sky #07B0F2 accents, no stock handshakes, subtle ${cn} wordmark on doc corner.`,
    `- **Body (paste-ready):**`,
    `Hi {{first_name}},`,
    ``,
    `If you are ${aud}, you have probably already tightened creative once or twice. The frustrating pattern we see in ${ind} is simpler: the ad promises one outcome, the landing page argues another, and the first follow-up email introduces a third. Buyers do not experience “more content”—they experience tax.`,
    ``,
    `${cn} maps one storyline from first touch through ${p1}. This note is not a pitch; it is a quick way to check whether your next dollar should go to creative, landing, or nurture—and why.`,
    ``,
    `— {{sender_name}}`,
    `- **Primary CTA (button):** Read the 3-slide “message → channel” sketch`,
    `- **Secondary CTA:** Reply “audit” for a 6-minute Loom walkthrough`,
    "",
    "## Email 2 — Awareness",
    `- **Subject line:** The proof ${aud} actually asked for last quarter`,
    `- **Preheader (inbox preview):** One before/after frame—no case-study theater.`,
    `- **Hero image prompt:** 1080×1080 static: before/after table (blurred client names), single bold metric callout, ${cn} color bars only, generous whitespace, caption-safe lower third.`,
    `- **Body (paste-ready):**`,
    `Hi {{first_name}},`,
    ``,
    `You opened the sketch—here is the “after” view we use with teams like yours: same spend window, one agreed metric, and the exact three surfaces we aligned first (usually hero, first nurture email, first sales deck slide).`,
    ``,
    `If this matches how you want to run ${p2} this quarter, the next email shows the mechanism in one screen flow—still one CTA.`,
    ``,
    `— {{sender_name}}`,
    `- **Primary CTA (button):** See the one-screen flow`,
    `- **Secondary CTA:** Forward to your growth lead`,
    "",
    "## Email 3 — Consideration",
    `- **Subject line:** Governance, ownership, and “who moves first?”`,
    `- **Preheader (inbox preview):** De-risking the engagement without slowing the deal.`,
    `- **Hero image prompt:** Simple RACI-style diagram on white, three swimlanes, navy text, one sky highlight on “owner” column; no logos except ${cn} small footer.`,
    `- **Body (paste-ready):**`,
    `Hi {{first_name}},`,
    ``,
    `By now you know we care about message-channel fit. The next question buyers ask—especially in ${ind}—is whether work will stall between marketing, sales, and delivery. Here is how we run the first 14 days: named owners, weekly ship checklist, and one shared metric so no one debates definitions mid-sprint.`,
    ``,
    `If your team already runs a strong ops rhythm, this will feel familiar. If not, it becomes your fastest win.`,
    ``,
    `— {{sender_name}}`,
    `- **Primary CTA (button):** Download the 14-day owner map (PDF)`,
    `- **Secondary CTA:** Book a 20-minute scope fit`,
    "",
    "## Email 4 — Consideration",
    `- **Subject line:** Outcome proof: what moved in 12 weeks (numbers + caveats)`,
    `- **Preheader (inbox preview):** Named window, named role, honest scope.`,
    `- **Hero image prompt:** Single chart: pipeline-sourced conversations vs. baseline; footnote text legible; brand colors; optional anonymized logo strip blurred.`,
    `- **Body (paste-ready):**`,
    `Hi {{first_name}},`,
    ``,
    `Here is the proof block buyers asked for most often: 12-week window, pipeline-sourced conversations (not vanity clicks), and the operational change that unlocked it—usually a tighter ${pillar} story on the first three buyer-facing surfaces.`,
    ``,
    `Caveat we always share: if your inbound is dominated by one channel, we re-weight the plan instead of forcing channel symmetry.`,
    ``,
    `— {{sender_name}}`,
    `- **Primary CTA (button):** Open the proof one-pager`,
    `- **Secondary CTA:** Reply “metric” to see the definition sheet`,
    "",
    "## Email 5 — Consideration",
    `- **Subject line:** How to evaluate partners (without the RFP theater)`,
    `- **Preheader (inbox preview):** Decision criteria + methodology—${cn} neutral tone.`,
    `- **Hero image prompt:** Checklist graphic: 5 criteria with icons (clarity, proof, owners, timeline, risk), monochrome + sky checkmarks.`,
    `- **Body (paste-ready):**`,
    `Hi {{first_name}},`,
    ``,
    `If you are comparing ${ind} partners this quarter, use the same five criteria we use internally: (1) single storyline test, (2) proof density on first pages, (3) named owners for 14 days, (4) honest “not a fit” language, (5) one metric you both agree to move first.`,
    ``,
    `We bias toward ${p3} because that is where compounding usually hides—and where drift quietly taxes CAC.`,
    ``,
    `— {{sender_name}}`,
    `- **Primary CTA (button):** Save the evaluation checklist`,
    `- **Secondary CTA:** Share with procurement / finance`,
    "",
    "## Email 6 — Decision",
    `- **Subject line:** What we deliver in the first 14 days (and what we do not)`,
    `- **Preheader (inbox preview):** Deliverables, timeline, fit boundaries.`,
    `- **Hero image prompt:** Three-column “Week 1–2 / 3–4 / 5+” roadmap graphic; clean sans; ${cn} header bar.`,
    `- **Body (paste-ready):**`,
    `Hi {{first_name}},`,
    ``,
    `Scope clarity reduces regret. In weeks 1–2 we lock the storyline and ship the first aligned surfaces. Weeks 3–4 add proof cadence and sales enablement snippets. Week 5+ scales what already moved your agreed metric.`,
    ``,
    `We are not a fit if you need instant net-new demand with zero narrative change—say so early; we will still leave you with a prioritized fix list.`,
    ``,
    `— {{sender_name}}`,
    `- **Primary CTA (button):** Book a 20-minute scope fit`,
    `- **Secondary CTA:** Reply “later” to pause the thread`,
    "",
    "## Email 7 — Decision",
    `- **Subject line:** Cohort / capacity note + one primary next step`,
    `- **Preheader (inbox preview):** Honest urgency only—no false scarcity.`,
    `- **Hero image prompt:** Calendar month view with limited highlighted slots; neutral background; text overlay max 6 words.`,
    `- **Body (paste-ready):**`,
    `Hi {{first_name}},`,
    ``,
    `We keep onboarding windows small so delivery keeps pace with promises. If ${p1} is still a priority this quarter, grab a slot this week—same scope-fit agenda: goal, first metric, honest fit.`,
    ``,
    `If timing slips, reply “Q3” and we will send one recap asset with no automated chase sequence.`,
    ``,
    `— {{sender_name}}`,
    `- **Primary CTA (button):** Pick a time — 20-minute scope fit`,
    `- **Secondary CTA:** Get the recap PDF instead`,
    "",
    "## Email 8 — Retention (customers & subscribers)",
    "_Use for active customers or opted-in subscribers — one chart, one recommendation._",
    "",
    `- **Subject line:** What changed in your funnel this month (1 chart)`,
    `- **Preheader (inbox preview):** Short win log + one upgrade path only if value is obvious.`,
    `- **Hero image prompt:** Single KPI tile + sparkline; brand colors; optional product UI crop.`,
    `- **Body (paste-ready):**`,
    `Hi {{first_name}},`,
    ``,
    `Quick monthly pulse: one chart on the metric we own together, one recommendation, one optional add-on only if it clears a value bar you already set.`,
    ``,
    `— {{sender_name}}`,
    `- **Primary CTA (button):** Open the monthly pulse`,
    "",
    "## Email 9 — Re-engagement (dormant or cold list)",
    "_Separate send — do not mix with Email 8. One subject line, one body, one primary CTA._",
    "",
    `- **Subject line:** A fresher angle on ${p2} (low friction)`,
    `- **Preheader (inbox preview):** One POV + one proof strip—no guilt trips.`,
    `- **Hero image prompt:** Single bold headline on textured paper photo; soft shadow; brand colors.`,
    `- **Body (paste-ready):**`,
    `Hi {{first_name}},`,
    ``,
    `We have not heard from you—totally fine. If tightening ${p2} for ${aud} is still the job to be done, here is one updated POV with a single CTA to re-enter without re-explaining your stack.`,
    ``,
    `— {{sender_name}}`,
    `- **Primary CTA (button):** See the refreshed POV`,
    `- **Secondary CTA:** Unsubscribe with one click`,
    "",
    "## 12-week operational rhythm (send rules)",
    "- Weeks 1–4: up to 2 emails/week (education + proof). Alternate long-form vs. short proof strip.",
    "- Weeks 5–8: 1–2 emails/week (deeper cases + offer ramp). Introduce one sales-assist touch when reply or high intent.",
    "- Weeks 9–12: refresh underperforming subject lines; pause any line below ~12% open after 3 sends; duplicate winner as static ad creative.",
    "",
    "## QA checklist before each send",
    "- One job per email, one primary CTA above the fold.",
    "- Subject line + preheader + hero all express the same promise.",
    "- Image prompts avoid unlicensed logos and competitor marks.",
    "- Proof numbers include timeframe and definition.",
  ].join("\n");
}
